project_name=vm-install-archetype-virtualbox
osname=ubuntu-12.04.2-server
preseed_filename=${osname}-preseed.cfg
project_dir=$project_name
ovf_full_path="${project_dir}"/"${project_name}".ovf
port_number=2222
username=$(grep '^d-i passwd/username string' $preseed_filename | awk '{print $NF}')
rsa_key_filename=vm_guest_id_rsa
packer_config_filename=vbox_${osname}-amd64_packer_config.json
